apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-documentation-service-to-delete"
  description: "Test service to be deleted"
  tags:
    - go
  annotations:
    github.com/project-slug: tamarakaufler/test-documentation-service-to-delete
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/tamarakaufler/test-documentation-service-to-delete
      title: GitHub repo
spec:
  type: documentation
  owner: backend
  lifecycle: experimental
  system: backend